name = "backend"
compatibility_date = "2024-08-30"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiM2FiYzMzM2EtN2Q1Yy00MDcxLWIzZDQtYzMwODkwODE0ZGQ4IiwidGVuYW50X2lkIjoiMGVkMDM0ZGU2OTkwNmQwYjQ5Y2VkMzYxM2NiM2Y1MTA1YjZkMjVjODVjMjBmZTYwNDIyZGY1ZmJmM2U2Njc0NSIsImludGVybmFsX3NlY3JldCI6IjdmNzhmN2E4LWYxMDQtNDk2YS05YjIwLTQ0MjQwNzE2MmMwMSJ9.rdLsutGab03F1AoHbzNN2D9DKBGwc0LitQiBMPsLSbM"
#compatibility_flags = [ "nodejs_compat" ]
#compatibility_flags = [ "nodejs_als" ]
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
JWT_TOKEN="H7c97@p6h2y$"
# [ai]
# binding = "AI"